format_version: 3
pipelines:
  test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      php:
        git: https://github.com/SoaadMahmoud/php
        username: soad
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:sph9tXSSQpwTFbGTfB9uXg==:Mf/6cmR01T3jxWUr0pPizw==
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - index.php
                command: cat
                run_if: passed 
